spring.application.name=vueloudea
spring.graphql.graphiql.enabled=true

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/codefactory_db
spring.datasource.username=deploy
spring.datasource.password=d3pl0y
spring.datasource.driver-class-name=org.postgresql.Driver
# Dialecto de PostgreSQL para Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Otras configuraciones opcionales
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework=DEBUG
logging.level.com.udea.vueloudea=DEBUG

spring.profiles.active=test

